import { IRC_FIELD_LABELS } from "./schema.irc.js";

export const FIELD_LABELS: Record<string, string> = {
  "meta.lastTouchedVersion": "Config Last Touched Version",
  "meta.lastTouchedAt": "Config Last Touched At",
  "update.channel": "Update Channel",
  "update.checkOnStart": "Update Check on Start",
  "diagnostics.enabled": "Diagnostics Enabled",
  "diagnostics.flags": "Diagnostics Flags",
  "diagnostics.otel.enabled": "OpenTelemetry Enabled",
  "diagnostics.otel.endpoint": "OpenTelemetry Endpoint",
  "diagnostics.otel.protocol": "OpenTelemetry Protocol",
  "diagnostics.otel.headers": "OpenTelemetry Headers",
  "diagnostics.otel.serviceName": "OpenTelemetry Service Name",
  "diagnostics.otel.traces": "OpenTelemetry Traces Enabled",
  "diagnostics.otel.metrics": "OpenTelemetry Metrics Enabled",
  "diagnostics.otel.logs": "OpenTelemetry Logs Enabled",
  "diagnostics.otel.sampleRate": "OpenTelemetry Trace Sample Rate",
  "diagnostics.otel.flushIntervalMs": "OpenTelemetry Flush Interval (ms)",
  "diagnostics.cacheTrace.enabled": "Cache Trace Enabled",
  "diagnostics.cacheTrace.filePath": "Cache Trace File Path",
  "diagnostics.cacheTrace.includeMessages": "Cache Trace Include Messages",
  "diagnostics.cacheTrace.includePrompt": "Cache Trace Include Prompt",
  "diagnostics.cacheTrace.includeSystem": "Cache Trace Include System",
  "agents.list.*.identity.avatar": "Identity Avatar",
  "agents.list.*.skills": "Agent Skill Filter",
  "agents.list[].runtime": "Agent Runtime",
  "agents.list[].runtime.type": "Agent Runtime Type",
  "agents.list[].runtime.acp": "Agent ACP Runtime",
  "agents.list[].runtime.acp.agent": "Agent ACP Harness Agent",
  "agents.list[].runtime.acp.backend": "Agent ACP Backend",
  "agents.list[].runtime.acp.mode": "Agent ACP Mode",
  "agents.list[].runtime.acp.cwd": "Agent ACP Working Directory",
  agents: "Agents",
  "agents.defaults": "Agent Defaults",
  "agents.list": "Agent List",
  gateway: "Gateway",
  "gateway.port": "Gateway Port",
  "gateway.mode": "Gateway Mode",
  "gateway.bind": "Gateway Bind Mode",
  "gateway.customBindHost": "Gateway Custom Bind Host",
  "gateway.controlUi": "Control UI",
  "gateway.controlUi.enabled": "Control UI Enabled",
  "gateway.auth": "Gateway Auth",
  "gateway.auth.mode": "Gateway Auth Mode",
  "gateway.auth.allowTailscale": "Gateway Auth Allow Tailscale Identity",
  "gateway.auth.rateLimit": "Gateway Auth Rate Limit",
  "gateway.auth.trustedProxy": "Gateway Trusted Proxy Auth",
  "gateway.trustedProxies": "Gateway Trusted Proxy CIDRs",
  "gateway.allowRealIpFallback": "Gateway Allow x-real-ip Fallback",
  "gateway.tools": "Gateway Tool Exposure Policy",
  "gateway.tools.allow": "Gateway Tool Allowlist",
  "gateway.tools.deny": "Gateway Tool Denylist",
  "gateway.channelHealthCheckMinutes": "Gateway Channel Health Check Interval (min)",
  "gateway.channelStaleEventThresholdMinutes": "Gateway Channel Stale Event Threshold (min)",
  "gateway.channelMaxRestartsPerHour": "Gateway Channel Max Restarts Per Hour",
  "gateway.tailscale": "Gateway Tailscale",
  "gateway.tailscale.mode": "Gateway Tailscale Mode",
  "gateway.tailscale.resetOnExit": "Gateway Tailscale Reset on Exit",
  "gateway.remote": "Remote Gateway",
  "gateway.remote.transport": "Remote Gateway Transport",
  "gateway.reload": "Config Reload",
  "gateway.tls": "Gateway TLS",
  "gateway.tls.enabled": "Gateway TLS Enabled",
  "gateway.tls.autoGenerate": "Gateway TLS Auto-Generate Cert",
  "gateway.tls.certPath": "Gateway TLS Certificate Path",
  "gateway.tls.keyPath": "Gateway TLS Key Path",
  "gateway.tls.caPath": "Gateway TLS CA Path",
  "gateway.http": "Gateway HTTP API",
  "gateway.http.endpoints": "Gateway HTTP Endpoints",
  "gateway.http.securityHeaders": "Gateway HTTP Security Headers",
  "gateway.http.securityHeaders.strictTransportSecurity": "Strict Transport Security Header",
  "gateway.remote.url": "Remote Gateway URL",
  "gateway.remote.sshTarget": "Remote Gateway SSH Target",
  "gateway.remote.sshIdentity": "Remote Gateway SSH Identity",
  "gateway.remote.token": "Remote Gateway Token",
  "gateway.remote.password": "Remote Gateway Password",
  "gateway.remote.tlsFingerprint": "Remote Gateway TLS Fingerprint",
  "gateway.auth.token": "Gateway Token",
  "gateway.auth.password": "Gateway Password",
  "tools.media.image.enabled": "Enable Image Understanding",
  "tools.media.image.maxBytes": "Image Understanding Max Bytes",
  "tools.media.image.maxChars": "Image Understanding Max Chars",
  "tools.media.image.prompt": "Image Understanding Prompt",
  "tools.media.image.timeoutSeconds": "Image Understanding Timeout (sec)",
  "tools.media.image.attachments": "Image Understanding Attachment Policy",
  "tools.media.image.models": "Image Understanding Models",
  "tools.media.image.scope": "Image Understanding Scope",
  "tools.media.models": "Media Understanding Shared Models",
  "tools.media.concurrency": "Media Understanding Concurrency",
  "tools.media.audio.enabled": "Enable Audio Understanding",
  "tools.media.audio.maxBytes": "Audio Understanding Max Bytes",
  "tools.media.audio.maxChars": "Audio Understanding Max Chars",
  "tools.media.audio.prompt": "Audio Understanding Prompt",
  "tools.media.audio.timeoutSeconds": "Audio Understanding Timeout (sec)",
  "tools.media.audio.language": "Audio Understanding Language",
  "tools.media.audio.attachments": "Audio Understanding Attachment Policy",
  "tools.media.audio.models": "Audio Understanding Models",
  "tools.media.audio.scope": "Audio Understanding Scope",
  "tools.media.video.enabled": "Enable Video Understanding",
  "tools.media.video.maxBytes": "Video Understanding Max Bytes",
  "tools.media.video.maxChars": "Video Understanding Max Chars",
  "tools.media.video.prompt": "Video Understanding Prompt",
  "tools.media.video.timeoutSeconds": "Video Understanding Timeout (sec)",
  "tools.media.video.attachments": "Video Understanding Attachment Policy",
  "tools.media.video.models": "Video Understanding Models",
  "tools.media.video.scope": "Video Understanding Scope",
  "tools.links.enabled": "Enable Link Understanding",
  "tools.links.maxLinks": "Link Understanding Max Links",
  "tools.links.timeoutSeconds": "Link Understanding Timeout (sec)",
  "tools.links.models": "Link Understanding Models",
  "tools.links.scope": "Link Understanding Scope",
  "tools.profile": "Tool Profile",
  "tools.entries": "Per-Tool Enable/Disable",
  "tools.alsoAllow": "Tool Allowlist Additions",
  "agents.list[].tools.profile": "Agent Tool Profile",
  "agents.list[].tools.alsoAllow": "Agent Tool Allowlist Additions",
  "tools.byProvider": "Tool Policy by Provider",
  "agents.list[].tools.byProvider": "Agent Tool Policy by Provider",
  "agents.list[].thinkingDefault": "Agent Default Thinking Level",
  "agents.list[].tools.entries": "Agent Per-Tool Enable/Disable",
  "tools.exec.applyPatch.enabled": "Enable apply_patch",
  "tools.exec.applyPatch.workspaceOnly": "apply_patch Workspace-Only",
  "tools.exec.applyPatch.allowModels": "apply_patch Model Allowlist",
  "tools.loopDetection.enabled": "Tool-loop Detection",
  "tools.loopDetection.historySize": "Tool-loop History Size",
  "tools.loopDetection.warningThreshold": "Tool-loop Warning Threshold",
  "tools.loopDetection.criticalThreshold": "Tool-loop Critical Threshold",
  "tools.loopDetection.globalCircuitBreakerThreshold": "Tool-loop Global Circuit Breaker Threshold",
  "tools.loopDetection.detectors.genericRepeat": "Tool-loop Generic Repeat Detection",
  "tools.loopDetection.detectors.knownPollNoProgress": "Tool-loop Poll No-Progress Detection",
  "tools.loopDetection.detectors.pingPong": "Tool-loop Ping-Pong Detection",
  "tools.fs.workspaceOnly": "Workspace-only FS tools",
  "tools.sessions.visibility": "Session Tools Visibility",
  "tools.exec.notifyOnExit": "Exec Notify On Exit",
  "tools.exec.notifyOnExitEmptySuccess": "Exec Notify On Empty Success",
  "tools.exec.approvalRunningNoticeMs": "Exec Approval Running Notice (ms)",
  "tools.exec.host": "Exec Host",
  "tools.exec.security": "Exec Security",
  "tools.exec.ask": "Exec Ask",
  "tools.exec.node": "Exec Node Binding",
  "tools.exec.pathPrepend": "Exec PATH Prepend",
  "tools.exec.safeBins": "Exec Safe Bins",
  "tools.message.allowCrossContextSend": "Allow Cross-Context Messaging",
  "tools.message.crossContext.allowWithinProvider": "Allow Cross-Context (Same Provider)",
  "tools.message.crossContext.allowAcrossProviders": "Allow Cross-Context (Across Providers)",
  "tools.message.crossContext.marker.enabled": "Cross-Context Marker",
  "tools.message.crossContext.marker.prefix": "Cross-Context Marker Prefix",
  "tools.message.crossContext.marker.suffix": "Cross-Context Marker Suffix",
  "tools.message.broadcast.enabled": "Enable Message Broadcast",
  "tools.web.search.enabled": "Enable Web Search Tool",
  "tools.web.search.provider": "Web Search Provider",
  "tools.web.search.apiKey": "Brave Search API Key",
  "tools.web.search.maxResults": "Web Search Max Results",
  "tools.web.search.timeoutSeconds": "Web Search Timeout (sec)",
  "tools.web.search.cacheTtlMinutes": "Web Search Cache TTL (min)",
  "tools.web.search.brave.mode": "Brave Search Mode",
  "tools.web.search.brave.llmContext.maxTokens": "Brave LLM Context Max Tokens",
  "tools.web.search.brave.llmContext.maxUrls": "Brave LLM Context Max URLs",
  "tools.web.search.brave.llmContext.thresholdMode": "Brave LLM Context Threshold",
  "tools.web.search.brave.llmContext.maxSnippets": "Brave LLM Context Max Snippets",
  "tools.web.search.brave.llmContext.maxTokensPerUrl": "Brave LLM Context Tokens/URL",
  "tools.web.search.brave.llmContext.maxSnippetsPerUrl": "Brave LLM Context Snippets/URL",
  "tools.web.fetch.enabled": "Enable Web Fetch Tool",
  "tools.web.fetch.maxChars": "Web Fetch Max Chars",
  "tools.web.fetch.timeoutSeconds": "Web Fetch Timeout (sec)",
  "tools.web.fetch.cacheTtlMinutes": "Web Fetch Cache TTL (min)",
  "tools.web.fetch.maxRedirects": "Web Fetch Max Redirects",
  "tools.web.fetch.userAgent": "Web Fetch User-Agent",
  "gateway.controlUi.basePath": "Control UI Base Path",
  "gateway.controlUi.root": "Control UI Assets Root",
  "gateway.controlUi.allowedOrigins": "Control UI Allowed Origins",
  "gateway.controlUi.allowInsecureAuth": "Allow Insecure Control UI Auth",
  "gateway.controlUi.dangerouslyDisableDeviceAuth": "Dangerously Disable Control UI Device Auth",
  "gateway.push": "Gateway Push Delivery",
  "gateway.push.apns": "Gateway APNs Delivery",
  "gateway.push.apns.relay": "Gateway APNs Relay",
  "gateway.push.apns.relay.baseUrl": "Gateway APNs Relay Base URL",
  "gateway.push.apns.relay.timeoutMs": "Gateway APNs Relay Timeout (ms)",
  "gateway.http.endpoints.chatCompletions.enabled": "OpenAI Chat Completions Endpoint",
  "gateway.reload.mode": "Config Reload Mode",
  "gateway.reload.debounceMs": "Config Reload Debounce (ms)",
  "gateway.nodes.browser.mode": "Gateway Node Browser Mode",
  "gateway.nodes.browser.node": "Gateway Node Browser Pin",
  "gateway.nodes.allowCommands": "Gateway Node Allowlist (Extra Commands)",
  "gateway.nodes.denyCommands": "Gateway Node Denylist",
  "nodeHost.browserProxy.enabled": "Node Browser Proxy Enabled",
  "nodeHost.browserProxy.allowProfiles": "Node Browser Proxy Allowed Profiles",
  "skills.load.watch": "Watch Skills",
  "skills.load.watchDebounceMs": "Skills Watch Debounce (ms)",
  "agents.defaults.workspace": "Workspace",
  "agents.defaults.repoRoot": "Repo Root",
  "agents.defaults.bootstrapMaxChars": "Bootstrap Max Chars",
  "agents.defaults.bootstrapTotalMaxChars": "Bootstrap Total Max Chars",
  "agents.defaults.bootstrap.injectMode": "Bootstrap Inject Mode",
  "agents.defaults.context.mode": "Context Mode",
  "agents.defaults.envelopeTimezone": "Envelope Timezone",
  "agents.defaults.envelopeTimestamp": "Envelope Timestamp",
  "agents.defaults.envelopeElapsed": "Envelope Elapsed",
  "agents.defaults.memorySearch": "Memory Search",
  "agents.defaults.memorySearch.enabled": "Enable Memory Search",
  "agents.defaults.memorySearch.sources": "Memory Search Sources",
  "agents.defaults.memorySearch.extraPaths": "Extra Memory Paths",
  "agents.defaults.memorySearch.multimodal": "Memory Search Multimodal",
  "agents.defaults.memorySearch.multimodal.enabled": "Enable Memory Search Multimodal",
  "agents.defaults.memorySearch.multimodal.modalities": "Memory Search Multimodal Modalities",
  "agents.defaults.memorySearch.multimodal.maxFileBytes": "Memory Search Multimodal Max File Bytes",
  "agents.defaults.memorySearch.experimental.sessionMemory":
    "Memory Search Session Index (Experimental)",
  "agents.defaults.memorySearch.provider": "Memory Search Provider",
  "agents.defaults.memorySearch.remote.baseUrl": "Remote Embedding Base URL",
  "agents.defaults.memorySearch.remote.apiKey": "Remote Embedding API Key",
  "agents.defaults.memorySearch.remote.headers": "Remote Embedding Headers",
  "agents.defaults.memorySearch.remote.batch.concurrency": "Remote Batch Concurrency",
  "agents.defaults.memorySearch.model": "Memory Search Model",
  "agents.defaults.memorySearch.outputDimensionality": "Memory Search Output Dimensionality",
  "agents.defaults.memorySearch.fallback": "Memory Search Fallback",
  "agents.defaults.memorySearch.local.modelPath": "Local Embedding Model Path",
  "agents.defaults.memorySearch.store.path": "Memory Search Index Path",
  "agents.defaults.memorySearch.store.vector.enabled": "Memory Search Vector Index",
  "agents.defaults.memorySearch.store.vector.extensionPath": "Memory Search Vector Extension Path",
  "agents.defaults.memorySearch.chunking.tokens": "Memory Chunk Tokens",
  "agents.defaults.memorySearch.chunking.overlap": "Memory Chunk Overlap Tokens",
  "agents.defaults.memorySearch.sync.onSessionStart": "Index on Session Start",
  "agents.defaults.memorySearch.sync.onSearch": "Index on Search (Lazy)",
  "agents.defaults.memorySearch.sync.watch": "Watch Memory Files",
  "agents.defaults.memorySearch.sync.watchDebounceMs": "Memory Watch Debounce (ms)",
  "agents.defaults.memorySearch.sync.sessions.deltaBytes": "Session Delta Bytes",
  "agents.defaults.memorySearch.sync.sessions.deltaMessages": "Session Delta Messages",
  "agents.defaults.memorySearch.sync.sessions.postCompactionForce":
    "Force Reindex After Compaction",
  "agents.defaults.memorySearch.query.maxResults": "Memory Search Max Results",
  "agents.defaults.memorySearch.query.minScore": "Memory Search Min Score",
  "agents.defaults.memorySearch.query.hybrid.enabled": "Memory Search Hybrid",
  "agents.defaults.memorySearch.query.hybrid.vectorWeight": "Memory Search Vector Weight",
  "agents.defaults.memorySearch.query.hybrid.textWeight": "Memory Search Text Weight",
  "agents.defaults.memorySearch.query.hybrid.candidateMultiplier":
    "Memory Search Hybrid Candidate Multiplier",
  "agents.defaults.memorySearch.cache.enabled": "Memory Search Embedding Cache",
  "agents.defaults.memorySearch.cache.maxEntries": "Memory Search Embedding Cache Max Entries",
  memory: "Memory",
  "memory.backend": "Memory Backend",
  "memory.citations": "Memory Citations Mode",
  "memory.qmd.command": "QMD Binary",
  "memory.qmd.includeDefaultMemory": "QMD Include Default Memory",
  "memory.qmd.paths": "QMD Extra Paths",
  "memory.qmd.paths.path": "QMD Path",
  "memory.qmd.paths.pattern": "QMD Path Pattern",
  "memory.qmd.paths.name": "QMD Path Name",
  "memory.qmd.sessions.enabled": "QMD Session Indexing",
  "memory.qmd.sessions.exportDir": "QMD Session Export Directory",
  "memory.qmd.sessions.retentionDays": "QMD Session Retention (days)",
  "memory.qmd.update.interval": "QMD Update Interval",
  "memory.qmd.update.debounceMs": "QMD Update Debounce (ms)",
  "memory.qmd.update.onBoot": "QMD Update on Startup",
  "memory.qmd.update.waitForBootSync": "QMD Wait for Boot Sync",
  "memory.qmd.update.embedInterval": "QMD Embed Interval",
  "memory.qmd.update.commandTimeoutMs": "QMD Command Timeout (ms)",
  "memory.qmd.update.updateTimeoutMs": "QMD Update Timeout (ms)",
  "memory.qmd.update.embedTimeoutMs": "QMD Embed Timeout (ms)",
  "memory.qmd.limits.maxResults": "QMD Max Results",
  "memory.qmd.limits.maxSnippetChars": "QMD Max Snippet Chars",
  "memory.qmd.limits.maxInjectedChars": "QMD Max Injected Chars",
  "memory.qmd.limits.timeoutMs": "QMD Search Timeout (ms)",
  "memory.qmd.scope": "QMD Surface Scope",
  "auth.profiles": "Auth Profiles",
  "auth.order": "Auth Profile Order",
  "auth.cooldowns.billingBackoffHours": "Billing Backoff (hours)",
  "auth.cooldowns.billingBackoffHoursByProvider": "Billing Backoff Overrides",
  "auth.cooldowns.billingMaxHours": "Billing Backoff Cap (hours)",
  "auth.cooldowns.failureWindowHours": "Failover Window (hours)",
  "agents.defaults.models": "Models",
  "agents.defaults.model.primary": "Primary Model",
  "agents.defaults.model.fallbacks": "Model Fallbacks",
  "agents.defaults.imageModel.primary": "Image Model",
  "agents.defaults.imageModel.fallbacks": "Image Model Fallbacks",
  "agents.defaults.humanDelay.mode": "Human Delay Mode",
  "agents.defaults.humanDelay.minMs": "Human Delay Min (ms)",
  "agents.defaults.humanDelay.maxMs": "Human Delay Max (ms)",
  "agents.defaults.cliBackends": "CLI Backends",
  "agents.defaults.compaction": "Compaction",
  "agents.defaults.compaction.mode": "Compaction Mode",
  "agents.defaults.compaction.reserveTokens": "Compaction Reserve Tokens",
  "agents.defaults.compaction.keepRecentTokens": "Compaction Keep Recent Tokens",
  "agents.defaults.compaction.reserveTokensFloor": "Compaction Reserve Token Floor",
  "agents.defaults.compaction.maxHistoryShare": "Compaction Max History Share",
  "agents.defaults.compaction.identifierPolicy": "Compaction Identifier Policy",
  "agents.defaults.compaction.identifierInstructions": "Compaction Identifier Instructions",
  "agents.defaults.compaction.recentTurnsPreserve": "Compaction Preserve Recent Turns",
  "agents.defaults.compaction.qualityGuard": "Compaction Quality Guard",
  "agents.defaults.compaction.qualityGuard.enabled": "Compaction Quality Guard Enabled",
  "agents.defaults.compaction.qualityGuard.maxRetries": "Compaction Quality Guard Max Retries",
  "agents.defaults.compaction.postIndexSync": "Compaction Post-Index Sync",
  "agents.defaults.compaction.postCompactionSections": "Post-Compaction Context Sections",
  "agents.defaults.compaction.timeoutSeconds": "Compaction Timeout (Seconds)",
  "agents.defaults.compaction.model": "Compaction Model Override",
  "agents.defaults.compaction.memoryFlush": "Compaction Memory Flush",
  "agents.defaults.compaction.memoryFlush.enabled": "Compaction Memory Flush Enabled",
  "agents.defaults.compaction.memoryFlush.softThresholdTokens":
    "Compaction Memory Flush Soft Threshold",
  "agents.defaults.compaction.memoryFlush.forceFlushTranscriptBytes":
    "Compaction Memory Flush Transcript Size Threshold",
  "agents.defaults.compaction.memoryFlush.prompt": "Compaction Memory Flush Prompt",
  "agents.defaults.compaction.memoryFlush.systemPrompt": "Compaction Memory Flush System Prompt",
  "agents.defaults.embeddedPi": "Embedded Pi",
  "agents.defaults.embeddedPi.projectSettingsPolicy": "Embedded Pi Project Settings Policy",
  "agents.defaults.heartbeat.directPolicy": "Heartbeat Direct Policy",
  "agents.list.*.heartbeat.directPolicy": "Heartbeat Direct Policy",
  "agents.defaults.heartbeat.suppressToolErrorWarnings": "Heartbeat Suppress Tool Error Warnings",
  "agents.defaults.sandbox.browser.network": "Sandbox Browser Network",
  "agents.defaults.sandbox.browser.cdpSourceRange": "Sandbox Browser CDP Source Port Range",
  "agents.defaults.sandbox.docker.dangerouslyAllowContainerNamespaceJoin":
    "Sandbox Docker Allow Container Namespace Join",
  commands: "Commands",
  "commands.native": "Native Commands",
  "commands.nativeSkills": "Native Skill Commands",
  "commands.text": "Text Commands",
  "commands.bash": "Allow Bash Chat Command",
  "commands.bashForegroundMs": "Bash Foreground Window (ms)",
  "commands.config": "Allow /config",
  "commands.debug": "Allow /debug",
  "commands.restart": "Allow Restart",
  "commands.useAccessGroups": "Use Access Groups",
  "commands.ownerAllowFrom": "Command Owners",
  "ui.seamColor": "Accent Color",
  "ui.assistant.name": "Assistant Name",
  "ui.assistant.avatar": "Assistant Avatar",
  "browser.evaluateEnabled": "Browser Evaluate Enabled",
  "browser.snapshotDefaults": "Browser Snapshot Defaults",
  "browser.snapshotDefaults.mode": "Browser Snapshot Mode",
  "browser.remoteCdpTimeoutMs": "Remote CDP Timeout (ms)",
  "browser.remoteCdpHandshakeTimeoutMs": "Remote CDP Handshake Timeout (ms)",
  "session.dmScope": "DM Session Scope",
  "session.agentToAgent.maxPingPongTurns": "Agent-to-Agent Ping-Pong Turns",
  "session.threadBindings": "Session Thread Bindings",
  "session.threadBindings.enabled": "Thread Binding Enabled",
  "session.threadBindings.idleHours": "Thread Binding Idle Timeout (hours)",
  "session.threadBindings.maxAgeHours": "Thread Binding Max Age (hours)",
  "session.maintenance": "Session Maintenance",
  "session.maintenance.mode": "Session Maintenance Mode",
  "session.maintenance.pruneAfter": "Session Prune After",
  "session.maintenance.pruneDays": "Session Prune Days (Deprecated)",
  "session.maintenance.maxEntries": "Session Max Entries",
  "session.maintenance.rotateBytes": "Session Rotate Size",
  "session.maintenance.resetArchiveRetention": "Session Reset Archive Retention",
  "session.maintenance.maxDiskBytes": "Session Max Disk Budget",
  "session.maintenance.highWaterBytes": "Session Disk High-water Target",
  cron: "Cron",
  "cron.enabled": "Cron Enabled",
  "cron.store": "Cron Store Path",
  "cron.maxConcurrentRuns": "Cron Max Concurrent Runs",
  "cron.retry": "Cron Retry Policy",
  "cron.retry.maxAttempts": "Cron Retry Max Attempts",
  "cron.retry.backoffMs": "Cron Retry Backoff (ms)",
  "cron.retry.retryOn": "Cron Retry Error Types",
  "cron.webhook": "Cron Legacy Webhook (Deprecated)",
  "cron.webhookToken": "Cron Webhook Bearer Token",
  "cron.sessionRetention": "Cron Session Retention",
  "cron.runLog": "Cron Run Log Pruning",
  "cron.runLog.maxBytes": "Cron Run Log Max Bytes",
  "cron.runLog.keepLines": "Cron Run Log Keep Lines",
  hooks: "Hooks",
  "hooks.enabled": "Hooks Enabled",
  "hooks.path": "Hooks Endpoint Path",
  "hooks.token": "Hooks Auth Token",
  "hooks.defaultSessionKey": "Hooks Default Session Key",
  "hooks.allowRequestSessionKey": "Hooks Allow Request Session Key",
  "hooks.allowedSessionKeyPrefixes": "Hooks Allowed Session Key Prefixes",
  "hooks.allowedAgentIds": "Hooks Allowed Agent IDs",
  "hooks.maxBodyBytes": "Hooks Max Body Bytes",
  "hooks.presets": "Hooks Presets",
  "hooks.transformsDir": "Hooks Transforms Directory",
  "hooks.mappings": "Hook Mappings",
  "hooks.mappings[].id": "Hook Mapping ID",
  "hooks.mappings[].match": "Hook Mapping Match",
  "hooks.mappings[].match.path": "Hook Mapping Match Path",
  "hooks.mappings[].match.source": "Hook Mapping Match Source",
  "hooks.mappings[].action": "Hook Mapping Action",
  "hooks.mappings[].wakeMode": "Hook Mapping Wake Mode",
  "hooks.mappings[].name": "Hook Mapping Name",
  "hooks.mappings[].agentId": "Hook Mapping Agent ID",
  "hooks.mappings[].sessionKey": "Hook Mapping Session Key",
  "hooks.mappings[].messageTemplate": "Hook Mapping Message Template",
  "hooks.mappings[].textTemplate": "Hook Mapping Text Template",
  "hooks.mappings[].deliver": "Hook Mapping Deliver Reply",
  "hooks.mappings[].allowUnsafeExternalContent": "Hook Mapping Allow Unsafe External Content",
  "hooks.mappings[].channel": "Hook Mapping Delivery Channel",
  "hooks.mappings[].to": "Hook Mapping Delivery Destination",
  "hooks.mappings[].model": "Hook Mapping Model Override",
  "hooks.mappings[].thinking": "Hook Mapping Thinking Override",
  "hooks.mappings[].timeoutSeconds": "Hook Mapping Timeout (sec)",
  "hooks.mappings[].transform": "Hook Mapping Transform",
  "hooks.mappings[].transform.module": "Hook Transform Module",
  "hooks.mappings[].transform.export": "Hook Transform Export",
  "hooks.gmail": "Gmail Hook",
  "hooks.gmail.account": "Gmail Hook Account",
  "hooks.gmail.label": "Gmail Hook Label",
  "hooks.gmail.topic": "Gmail Hook Pub/Sub Topic",
  "hooks.gmail.subscription": "Gmail Hook Subscription",
  "hooks.gmail.pushToken": "Gmail Hook Push Token",
  "hooks.gmail.hookUrl": "Gmail Hook Callback URL",
  "hooks.gmail.includeBody": "Gmail Hook Include Body",
  "hooks.gmail.maxBytes": "Gmail Hook Max Body Bytes",
  "hooks.gmail.renewEveryMinutes": "Gmail Hook Renew Interval (min)",
  "hooks.gmail.allowUnsafeExternalContent": "Gmail Hook Allow Unsafe External Content",
  "hooks.gmail.serve": "Gmail Hook Local Server",
  "hooks.gmail.serve.bind": "Gmail Hook Server Bind Address",
  "hooks.gmail.serve.port": "Gmail Hook Server Port",
  "hooks.gmail.serve.path": "Gmail Hook Server Path",
  "hooks.gmail.tailscale": "Gmail Hook Tailscale",
  "hooks.gmail.tailscale.mode": "Gmail Hook Tailscale Mode",
  "hooks.gmail.tailscale.path": "Gmail Hook Tailscale Path",
  "hooks.gmail.tailscale.target": "Gmail Hook Tailscale Target",
  "hooks.gmail.model": "Gmail Hook Model Override",
  "hooks.gmail.thinking": "Gmail Hook Thinking Override",
  "hooks.internal": "Internal Hooks",
  "hooks.internal.enabled": "Internal Hooks Enabled",
  "hooks.internal.handlers": "Internal Hook Handlers",
  "hooks.internal.handlers[].event": "Internal Hook Event",
  "hooks.internal.handlers[].module": "Internal Hook Module",
  "hooks.internal.handlers[].export": "Internal Hook Export",
  "hooks.internal.entries": "Internal Hook Entries",
  "hooks.internal.load": "Internal Hook Loader",
  "hooks.internal.load.extraDirs": "Internal Hook Extra Directories",
  "hooks.internal.installs": "Internal Hook Install Records",
  web: "Web Channel",
  "web.enabled": "Web Channel Enabled",
  "web.heartbeatSeconds": "Web Channel Heartbeat Interval (sec)",
  "web.reconnect": "Web Channel Reconnect Policy",
  "web.reconnect.initialMs": "Web Reconnect Initial Delay (ms)",
  "web.reconnect.maxMs": "Web Reconnect Max Delay (ms)",
  "web.reconnect.factor": "Web Reconnect Backoff Factor",
  "web.reconnect.jitter": "Web Reconnect Jitter",
  "web.reconnect.maxAttempts": "Web Reconnect Max Attempts",
  discovery: "Discovery",
  "discovery.wideArea": "Wide-area Discovery",
  "discovery.wideArea.enabled": "Wide-area Discovery Enabled",
  "discovery.wideArea.domain": "Wide-area Discovery Domain",
  "discovery.mdns": "mDNS Discovery",
  canvasHost: "Canvas Host",
  "canvasHost.enabled": "Canvas Host Enabled",
  "canvasHost.root": "Canvas Host Root Directory",
  "canvasHost.port": "Canvas Host Port",
  "canvasHost.liveReload": "Canvas Host Live Reload",
  talk: "Talk",
  "talk.voiceId": "Talk Voice ID",
  "talk.voiceAliases": "Talk Voice Aliases",
  "talk.modelId": "Talk Model ID",
  "talk.outputFormat": "Talk Output Format",
  "talk.interruptOnSpeech": "Talk Interrupt on Speech",
  "talk.silenceTimeoutMs": "Talk Silence Timeout (ms)",
  messages: "Messages",
  "messages.messagePrefix": "Inbound Message Prefix",
  "messages.responsePrefix": "Outbound Response Prefix",
  "messages.groupChat": "Group Chat Rules",
  "messages.groupChat.mentionPatterns": "Group Mention Patterns",
  "messages.groupChat.historyLimit": "Group History Limit",
  "messages.queue": "Inbound Queue",
  "messages.queue.mode": "Queue Mode",
  "messages.queue.byChannel": "Queue Mode by Channel",
  "messages.queue.debounceMs": "Queue Debounce (ms)",
  "messages.queue.debounceMsByChannel": "Queue Debounce by Channel (ms)",
  "messages.queue.cap": "Queue Capacity",
  "messages.queue.drop": "Queue Drop Strategy",
  "messages.inbound": "Inbound Debounce",
  "messages.suppressToolErrors": "Suppress Tool Error Warnings",
  "messages.ackReaction": "Ack Reaction Emoji",
  "messages.ackReactionScope": "Ack Reaction Scope",
  "messages.inbound.debounceMs": "Inbound Message Debounce (ms)",
  "talk.apiKey": "Talk API Key",
  "channels.whatsapp": "WhatsApp",
  "channels.telegram": "Telegram",
  "channels.telegram.customCommands": "Telegram Custom Commands",
  "channels.discord": "Discord",
  "channels.slack": "Slack",
  "channels.mattermost": "Mattermost",
  "channels.signal": "Signal",
  "channels.imessage": "iMessage",
  "channels.bluebubbles": "BlueBubbles",
  "channels.msteams": "MS Teams",
  ...IRC_FIELD_LABELS,
  "channels.telegram.botToken": "Telegram Bot Token",
  "channels.telegram.dmPolicy": "Telegram DM Policy",
  "channels.telegram.streamMode": "Telegram Stream Mode",
  "channels.telegram.draftChunk.minChars": "Telegram Draft Chunk Min Chars",
  "channels.telegram.draftChunk.maxChars": "Telegram Draft Chunk Max Chars",
  "channels.telegram.draftChunk.breakPreference": "Telegram Draft Chunk Break Preference",
  "channels.telegram.retry.attempts": "Telegram Retry Attempts",
  "channels.telegram.retry.minDelayMs": "Telegram Retry Min Delay (ms)",
  "channels.telegram.retry.maxDelayMs": "Telegram Retry Max Delay (ms)",
  "channels.telegram.retry.jitter": "Telegram Retry Jitter",
  "channels.telegram.network.autoSelectFamily": "Telegram autoSelectFamily",
  "channels.telegram.timeoutSeconds": "Telegram API Timeout (seconds)",
  "channels.telegram.capabilities.inlineButtons": "Telegram Inline Buttons",
  "channels.whatsapp.dmPolicy": "WhatsApp DM Policy",
  "channels.whatsapp.selfChatMode": "WhatsApp Self-Phone Mode",
  "channels.whatsapp.debounceMs": "WhatsApp Message Debounce (ms)",
  "channels.signal.dmPolicy": "Signal DM Policy",
  "channels.imessage.dmPolicy": "iMessage DM Policy",
  "channels.bluebubbles.dmPolicy": "BlueBubbles DM Policy",
  "channels.discord.dmPolicy": "Discord DM Policy",
  "channels.discord.dm.policy": "Discord DM Policy",
  "channels.discord.retry.attempts": "Discord Retry Attempts",
  "channels.discord.retry.minDelayMs": "Discord Retry Min Delay (ms)",
  "channels.discord.retry.maxDelayMs": "Discord Retry Max Delay (ms)",
  "channels.discord.retry.jitter": "Discord Retry Jitter",
  "channels.discord.maxLinesPerMessage": "Discord Max Lines Per Message",
  "channels.discord.ui.components.accentColor": "Discord Component Accent Color",
  "channels.discord.intents.presence": "Discord Presence Intent",
  "channels.discord.intents.guildMembers": "Discord Guild Members Intent",
  "channels.discord.pluralkit.enabled": "Discord PluralKit Enabled",
  "channels.discord.pluralkit.token": "Discord PluralKit Token",
  "channels.discord.activity": "Discord Presence Activity",
  "channels.discord.status": "Discord Presence Status",
  "channels.discord.activityType": "Discord Presence Activity Type",
  "channels.discord.activityUrl": "Discord Presence Activity URL",
  "channels.slack.dm.policy": "Slack DM Policy",
  "channels.slack.dmPolicy": "Slack DM Policy",
  "channels.slack.allowBots": "Slack Allow Bot Messages",
  "channels.discord.token": "Discord Bot Token",
  "channels.slack.botToken": "Slack Bot Token",
  "channels.slack.appToken": "Slack App Token",
  "channels.slack.userToken": "Slack User Token",
  "channels.slack.userTokenReadOnly": "Slack User Token Read Only",
  "channels.slack.capabilities.interactiveReplies": "Slack Interactive Replies",
  "channels.slack.streaming": "Slack Streaming Mode",
  "channels.slack.nativeStreaming": "Slack Native Streaming",
  "channels.slack.streamMode": "Slack Stream Mode (Legacy)",
  "channels.slack.thread.historyScope": "Slack Thread History Scope",
  "channels.slack.thread.inheritParent": "Slack Thread Parent Inheritance",
  "channels.slack.thread.initialHistoryLimit": "Slack Thread Initial History Limit",
  "channels.mattermost.botToken": "Mattermost Bot Token",
  "channels.mattermost.baseUrl": "Mattermost Base URL",
  "channels.mattermost.chatmode": "Mattermost Chat Mode",
  "channels.mattermost.oncharPrefixes": "Mattermost Onchar Prefixes",
  "channels.mattermost.requireMention": "Mattermost Require Mention",
  "channels.signal.account": "Signal Account",
  "channels.imessage.cliPath": "iMessage CLI Path",
  "agents.list[].skills": "Agent Skill Filter",
  "agents.list[].identity.avatar": "Agent Avatar",
  "discovery.mdns.mode": "mDNS Discovery Mode",
  "plugins.enabled": "Enable Plugins",
  "plugins.allow": "Plugin Allowlist",
  "plugins.deny": "Plugin Denylist",
  "plugins.load.paths": "Plugin Load Paths",
  "plugins.slots": "Plugin Slots",
  "plugins.slots.memory": "Memory Plugin",
  "plugins.entries": "Plugin Entries",
  "plugins.entries.*.enabled": "Plugin Enabled",
  "plugins.entries.*.config": "Plugin Config",
  "plugins.installs": "Plugin Install Records",
  "plugins.installs.*.source": "Plugin Install Source",
  "plugins.installs.*.spec": "Plugin Install Spec",
  "plugins.installs.*.sourcePath": "Plugin Install Source Path",
  "plugins.installs.*.installPath": "Plugin Install Path",
  "plugins.installs.*.version": "Plugin Install Version",
  "plugins.installs.*.installedAt": "Plugin Install Time",
};
